{
 "title": "Grafana metrics",
 "description": "Metrics about Grafana",
 "tags": [
  "grafana",
  "application",
  "showcase"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(loki_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dashboard count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_totals_dashboard{job=\"integrations/kubernetes/grafana\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "User count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_total_users{job=\"integrations/kubernetes/grafana\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Playlist count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_total_playlists{job=\"integrations/kubernetes/grafana\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, process_resident_memory_bytes{job=\"integrations/kubernetes/grafana\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Grafana version",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "topk(1, grafana_info{cluster=\"$cluster\"} or grafana_build_info{cluster=\"$cluster\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "http status codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status_code) (grafana_http_request_duration_seconds_sum{namespace=\"grafana\",cluster=\"$cluster\"})",
     "legendFormat": "{{statuscode}}",
     "target": "dev.grafana.cb-office.alerting.active_alerts"
    }
   ]
  },
  {
   "title": "Requests by routing group",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code) (irate(grafana_api_response_status_total{cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "api {{code}}"
    },
    {
     "expr": "sum by(code) (irate(grafana_proxy_response_status_total{namespace=\"grafana\",cluster=\"$cluster\"}[1m]))",
     "legendFormat": "proxy {{code}}"
    },
    {
     "expr": "sum by(code) (irate(grafana_page_response_status_total{namespace=\"grafana\",cluster=\"$cluster\"}[1m]))",
     "legendFormat": "web {{code}}"
    }
   ]
  },
  {
   "title": "Most used handlers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(handler) (grafana_http_request_duration_seconds_sum{namespace=\"grafana\",cluster=\"$cluster\"})",
     "legendFormat": "{{statuscode}}",
     "target": "dev.grafana.cb-office.alerting.active_alerts"
    }
   ]
  },
  {
   "title": "Grafana performance",
   "type": "timeseries",
   "description": "Aggregated over all Grafana nodes.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{service=\"grafana\",cluster=\"$cluster\"})",
     "legendFormat": "go routines",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"grafana_metrics\",cluster=\"$cluster\"})",
     "legendFormat": "memory usage"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Alerts Alerting",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_alerts{cluster=\"$cluster\", state=\"alerting\"}"
    }
   ]
  },
  {
   "title": "Alerts Error",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_alerts{cluster=\"$cluster\", state=\"error\"}"
    }
   ]
  },
  {
   "title": "Alerts NoData",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_alerts{cluster=\"$cluster\", state=\"nodata\"}"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_alerts{cluster=\"$cluster\", state=\"pending\"}"
    }
   ]
  },
  {
   "title": "Alerts Normal",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_alerts{cluster=\"$cluster\", state=\"normal\"}"
    }
   ]
  },
  {
   "title": "Grafana active alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(state) (grafana_alerting_alerts{cluster=\"$cluster\", namespace=\"grafana\"})",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}