{
 "title": "LGTM Stats",
 "tags": [
  "k8s",
  "iptor",
  "stats",
  "showcase"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(cortex_build_info,cluster)"
    }
   },
   {
    "name": "mimirTenant",
    "label": "Mimir Tenants",
    "query": {
     "query": "label_values(cortex_ingester_active_series,user)"
    }
   },
   {
    "name": "tempoTenant",
    "label": "Tempo Tenants",
    "query": {
     "query": "label_values(tempodb_blocklist_length,tenant)"
    }
   },
   {
    "name": "lokiTenant",
    "label": "Loki Tenants",
    "query": {
     "query": "label_values(loki_distributor_bytes_received_total,tenant)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tenant Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count(cortex_ingester_active_series{cluster=~\"$cluster\", user=~\".*\"}) by (user))",
     "legendFormat": "Mimir Tenants"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by(cluster) (cortex_alertmanager_tenants_discovered{cluster=~\"$cluster\", job=\"mimir/mimir\"})",
     "legendFormat": "Alertmanager Tenants"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count(loki_distributor_bytes_received_total{cluster=~\"$cluster\", tenant=~\".*\"}) by (tenant))",
     "legendFormat": "Loki Tenants"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count(tempodb_blocklist_length{cluster=~\"$cluster\", tenant=~\".*\"}) by (tenant))",
     "legendFormat": "Tempo Tenants"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by(cluster) (grafana_stat_total_orgs{cluster=~\"$cluster\"})",
     "legendFormat": "Grafana Total Orgs"
    }
   ]
  },
  {
   "title": "Tenants and Orgs over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "count(count(cortex_ingester_active_series{cluster=~\"$cluster\", user=~\".*\"}) by (user))",
     "legendFormat": "Mimir Tenants"
    },
    {
     "expr": "max by(cluster) (cortex_alertmanager_tenants_discovered{cluster=~\"$cluster\", job=\"mimir/mimir\"})",
     "legendFormat": "Alertmanager Tenants"
    },
    {
     "expr": "count(count(loki_distributor_bytes_received_total{cluster=~\"$cluster\", tenant=~\".*\"}) by (tenant))",
     "legendFormat": "Loki Tenants"
    },
    {
     "expr": "count(count(tempodb_blocklist_length{cluster=~\"$cluster\", tenant=~\".*\"}) by (tenant))",
     "legendFormat": "Tempo Tenants"
    },
    {
     "expr": "max by(cluster) (grafana_stat_total_orgs{cluster=~\"$cluster\"})",
     "legendFormat": "Grafana Orgs"
    }
   ]
  },
  { "title": "Global Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Grafana Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "grafana_build_info" }
   ]
  },
  {
   "title": "Grafana Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cluster) (grafana_live_node_num_users{cluster=\"$cluster\"})",
     "legendFormat": "Live Users"
    },
    {
     "expr": "max by(cluster) (grafana_stat_active_users{cluster=\"$cluster\"})",
     "legendFormat": "Users within 30 days"
    },
    {
     "expr": "max by(cluster) (grafana_stat_total_users{cluster=\"$cluster\"})",
     "legendFormat": "Total Users"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_totals_dashboard{cluster=~\"$cluster\"})",
     "legendFormat": "Dashboard count"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_total_playlists{cluster=~\"$cluster\"})",
     "legendFormat": "Playlist count"
    }
   ]
  },
  {
   "title": "Alerts Normal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cluster) (grafana_alerting_alerts{cluster=\"$cluster\", state=\"normal\"})"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cluster) (grafana_alerting_alerts{cluster=\"$cluster\", state=\"pending\"})"
    }
   ]
  },
  {
   "title": "Alerts NoData",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cluster) (grafana_alerting_alerts{cluster=\"$cluster\", state=\"nodata\"})"
    }
   ]
  },
  {
   "title": "Alerts Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cluster) (grafana_alerting_alerts{cluster=\"$cluster\", state=\"error\"})"
    }
   ]
  },
  {
   "title": "Alerts Alerting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cluster) (grafana_alerting_alerts{cluster=\"$cluster\", state=\"alerting\"})"
    }
   ]
  },
  {
   "title": "Mimir Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mimir_build_info" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster_namespace_job:cortex_distributor_received_samples:rate5m{cluster=~\"$cluster\", job=\"mimir/mimir\"}",
     "legendFormat": "Samples Per Second"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cortex_ingester_memory_series{cluster=~\"$cluster\", job=\"mimir/mimir\"})",
     "legendFormat": "Series In Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cortex_ingester_memory_series{cluster=~\"$cluster\", job=\"mimir/mimir\"}\r\n/ on(cluster, namespace) group_left\r\nmax by (cluster, namespace) (cortex_distributor_replication_factor{cluster=~\"$cluster\", job=\"mimir/mimir\"}))\r\n",
     "legendFormat": "Active Series"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "e/ps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cortex_prometheus_rule_evaluations_total{cluster=~\"$cluster\", job=\"mimir/mimir\"}[$__rate_interval]))\r\n-\r\nsum(rate(cortex_prometheus_rule_evaluation_failures_total{cluster=~\"$cluster\", job=\"mimir/mimir\"}[$__rate_interval]))\r\n",
     "legendFormat": "Ruler Evaluations Per Second"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "q/ps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(cortex_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"mimir\", container=\"query-frontend\", route=~\"prometheus_api_v1_.+\"}[$__rate_interval]))",
     "legendFormat": "Queries Per Second"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "n/ps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(rate(cortex_alertmanager_alerts_received_total{cluster=\"$cluster\"}[5m])[24h:5m]))",
     "legendFormat": "Alertmanager Notifications p/s /24h"
    }
   ]
  },
  {
   "title": "Alerts Normal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_job_pod:cortex_alertmanager_alerts:sum{cluster=~\"$cluster\", job=\"mimir/mimir\"})",
     "legendFormat": "Total Alerts"
    }
   ]
  },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "Loki Max Logs Stored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(cluster) (loki_ingester_chunk_stored_bytes_total{cluster=\"$cluster\", namespace=\"loki\", tenant=~\"$lokiTenant\"}))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Log Message Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(log_messages_total{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(loki_store_series_total{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Store Total $Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(loki_ingester_chunk_stored_bytes_total{cluster=\"$cluster\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cortex_prometheus_notifications_alertmanagers_discovered{cluster=\"$cluster\", namespace=\"loki\"}"
    }
   ]
  },
  {
   "title": "Rules Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cortex_prometheus_rule_group_rules{cluster=\"$cluster\", namespace=\"loki\"})"
    }
   ]
  },
  {
   "title": "Tempo Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "tempo_build_info" }
   ]
  },
  {
   "title": "Tempo Max Traces Stored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(cluster) (tempodb_backend_bytes_total{namespace=\"tempo\", cluster=\"$cluster\", tenant=~\"$tempoTenant\"}))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Spans Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (tempo_distributor_spans_received_total{cluster=\"$cluster\", namespace=\"tempo\"})"
    }
   ]
  },
  {
   "title": "Traces Created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (tempo_ingester_traces_created_total{cluster=\"$cluster\", namespace=\"tempo\"})"
    }
   ]
  },
  {
   "title": "Grafana Live Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max by(cluster) (grafana_live_node_num_users{cluster=\"$cluster\"})",
     "legendFormat": "Live Users"
    },
    {
     "expr": "max by(cluster) (grafana_stat_active_users{cluster=\"$cluster\"})",
     "legendFormat": "Users within 30 days"
    },
    {
     "expr": "max by(cluster) (grafana_stat_total_users{cluster=\"$cluster\"})",
     "legendFormat": "Total Users"
    }
   ]
  },
  { "title": "Per Tenant Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Mimir Series In Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(user) (cortex_ingester_active_series{cluster=~\"$cluster\", job=\"mimir/mimir\", user=~\"$mimirTenant\"}))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Loki Max Logs Stored per Tenant",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(tenant) (loki_ingester_chunk_stored_bytes_total{cluster=\"$cluster\", namespace=\"loki\", tenant=~\"$lokiTenant\"}))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Tempo Max Traces Stored per Tenant",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(tenant) (tempodb_backend_bytes_total{namespace=\"tempo\", cluster=\"$cluster\", tenant=~\"$tempoTenant\"}))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Mimir Series In Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(user) (cortex_ingester_active_series{cluster=~\"$cluster\", job=\"mimir/mimir\", user=~\"$mimirTenant\"})",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Loki Rate MBs per Tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by(tenant) (rate(loki_ingester_chunk_stored_bytes_total{cluster=\"$cluster\", namespace=\"loki\", tenant=~\"$lokiTenant\"}[5m])))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Tempo Bytes Received Rate per Tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(tenant) (rate(tempo_distributor_bytes_received_total{namespace=\"tempo\", cluster=\"$cluster\", tenant=~\"$tempoTenant\"}[$__rate_interval]))",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}