{
 "title": "Blackbox Exporter",
 "description": "A dashboard that monitors the blackbox_metrics_job.",
 "tags": [ "showcase" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "targets",
    "label": "targets",
    "query": {
     "query": "label_values(probe_success{cluster=\"$cluster\"},target)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(probe_success,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Probes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(probe_http_version{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Probes Success %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(probe_success{job=\"blackbox_metrics_job\", cluster=\"$cluster\"} == 1) OR vector(0)) / count(probe_http_version{job=\"blackbox_metrics_job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Probes SSL %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(probe_http_ssl{job=\"blackbox_metrics_job\", cluster=\"$cluster\"} == 1) / count(probe_http_version{job=\"blackbox_metrics_job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{job=\"blackbox_metrics_job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Certs expiring in less than 30 days",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{cluster=\"$cluster\"} - time() < (3600 * 24 * 30) "
    }
   ]
  },
  {
   "title": "Recent Probe Failures",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by(target) (probe_success{job=\"blackbox_metrics_job\", cluster=\"$cluster\"} != 1)"
    }
   ]
  },
  {
   "title": "$targets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "targets",
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{target=~\"$targets\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Latest Response Code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{target=~\"$targets\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "HTTP duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (probe_http_duration_seconds{target=~\"$targets\", cluster=\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{target=~\"$targets\", cluster=\"$cluster\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{target=~\"$targets\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "SSL Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_tls_version_info{target=~\"$targets\", cluster=\"$cluster\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Redirects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_http_redirects{target=~\"$targets\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_http_version{target=~\"$targets\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "HTTP phase percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{target=~\"$targets\", cluster=\"$cluster\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "SSL Certificate Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$targets\", cluster=\"$cluster\"} - time()"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$targets\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{target=~\"$targets\", cluster=\"$cluster\"}"
    }
   ]
  }
 ]
}