upstream alloy_backend {
    server 10.0.0.10:12345;
}

server {
  listen 9456 ssl;
  server_name home.example.com;
  ssl_certificate /Certificate/certificate.pem;
  ssl_certificate_key /Certificate/privateKey.key;

  location / {
      proxy_http_version 1.1;
      proxy_pass http://alloy_backend/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # websockets
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      # Allow framing in HA dashboard
      proxy_hide_header X-Frame-Options;
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header Content-Security-Policy "frame-ancestors 'self' https://home.example.com:8123 https://home.example.com:8124" always;

      proxy_redirect off;
  }
}
