upstream coder_backend {
    server 10.0.0.10:8444;
    keepalive 32;
}

server {
	listen 9454 ssl;
	server_name home.example.com;

	# SSL
	ssl_certificate /Certificate/certificate.pem;
	ssl_certificate_key /Certificate/privateKey.key;

	client_max_body_size 100M;

    location / {
    #   auth_basic "Code Login";
    #   auth_basic_user_file /etc/apache2/.htpasswd;

      proxy_pass http://coder_backend;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header Sec-WebSocket-Protocol $http_sec_websocket_protocol;

      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Port $server_port;

      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Accept-Encoding gzip;

      proxy_read_timeout 3600s;
      proxy_send_timeout 3600s;

      proxy_buffering off;
      proxy_redirect off;
    }
}
