upstream portainer {
    server 10.0.0.10:9000;
}

server {
  listen 9453 ssl;
  server_name home.example.com;
  ssl_certificate /Certificate/certificate.pem;
  ssl_certificate_key /Certificate/privateKey.key;


  location /portainer/ {
      proxy_http_version 1.1;
      proxy_pass http://portainer/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_set_header X-Forwarded-Prefix /portainer;

      # websockets
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Origin $scheme://$host;

      # REMOVE Portainer anti-iframe headers
      proxy_hide_header Content-Security-Policy;
      proxy_hide_header X-Frame-Options;

      # ADD headers that allow HA to frame it
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header Content-Security-Policy "frame-ancestors 'self' https://home.example.com:8123 https://home.example.com:8124" always;

      proxy_redirect off;
  }
  location /portainer/api/websocket/ {
      proxy_http_version 1.1;
      proxy_set_header Upgrade    $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_pass http://portainer/api/websocket/;
  }
}
